### What is PyTorch?
- PyTorch is a open-source deep learning framework designed to simplify the process of building of neural networks and machine learning models.
- With its dynamic computation graph, it allows developers to modify the neteork's behaviour in real-time.

### What is Tensors?
- Tensor is a multi-dimensional array of elements of a single data type which is very similar with numpy's ndarray.
- When the dimension is zero, it can be called a scaler.
- When the dimension is 2, it can be called a matrix.
- When the dimension is greater than 2, it can be called a tensor.


In [5]:
import torch
import numpy as np

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# print versions
print('torch versions:', torch.__version__)
print('numpy versions:', np.__version__)

torch versions: 2.10.0+cpu
numpy versions: 2.4.2


### What is Tensor Initialization?
- This code creates a 2x3 PyTorch tensor with float32 data type, assigns it to a specified device(CPU or GPU), and enables gradient tracking for backpropagation.

In [17]:
import torch

my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                        requires_grad=True)
print(my_tensor)
print('Data Type:',my_tensor.dtype)
print('Shape of Tensor:', my_tensor.shape)
print('Requires Gradient:', my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
Data Type: torch.float32
Shape of Tensor: torch.Size([2, 3])
Requires Gradient: True


### Other Common Tensor Initialization Methods:
- Empty Tensor - Creates an uninitialized 3x3 tensor (random values).
- Zeros Tensor - Creates a 3x3 tensor filled with zeros.
- Random Tensor - Generate 3x3 tensor with random values between 0 and 1.
- Ones Tensor - Creates 3x3 tensor filled with ones.
- Identity Matrix - Generates a 4x4 identity matrix(diagonal ones).
- Arange Tensor - Creates a 1D tensor with values from 0 to 4(step of 1).
- Linspace Tensor - Generates 5 evenly spaced values between 0.1 and 1.
- Normal Distribution Tensor - Fills a tensor with values from a normal(Gaussian) distribution with mean 0 and std 1.
- Uniform Distribution Tensor - Fills a tensor with values from a uniform distribution between 0 and 1.
- Diagonal Tensor - Creates a 4x4 diagonal with ones along the diagonal and zeros elsewhere.

In [18]:
# Create an empty tensor of size 3x3
x = torch.empty(3, 3)
print('Empty Tensor:\n', x)

# Create a tensor filled with zeros
x = torch.zeros(3, 3)
print('Zeros Tensor:\n', x)

# Create a tensor with random values
x = torch.rand(3, 3)
print('Random Tensor:', x)

# Create a tensor filled with ones
x = torch.ones(3, 3)
print('Ones Tensor:\n', x)

# Create a identity matrix
x = torch.eye(4, 4)
print('Identity Matrix:\n', x)

# Create a tensor using arange
x = torch.arange(5)
print('Arange Tensor:\n', x)

# Create a tensor using linspace
x = torch.linspace(0.1, 1, 5)
print('Linspace Tensor:\n', x)

# Create a tensor with values from a normal distribution
x = torch.empty(1, 5).normal_(mean=0, std=1)
print('Normal Distribution Tensor:\n', x)

# Create a tensor with values drawn from a uniform distribution
x = torch.empty(1, 5).uniform_(0, 1)
print('Uniform Distributed Tensor:\n', x)

Empty Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Random Tensor: tensor([[0.8886, 0.5235, 0.7916],
        [0.8543, 0.3665, 0.7609],
        [0.3791, 0.8391, 0.2593]])
Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Identity Matrix:
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Arange Tensor:
 tensor([0, 1, 2, 3, 4])
Linspace Tensor:
 tensor([0.1000, 0.3250, 0.5500, 0.7750, 1.0000])
Normal Distribution Tensor:
 tensor([[ 1.3066,  0.9016, -0.5928,  0.8731, -0.3008]])
Uniform Distributed Tensor:
 tensor([[0.3827, 0.3927, 0.2302, 0.7319, 0.1702]])


### Tensor Type Conversion
- Creates a Tensor with [0,1,2,3] and demonstartes type conversion to boolean, int16, int64, float32, float64.
  

In [22]:
# Create a tensor with arange values
tensor = torch.arange(4)
print('Tensor:\n', tensor)

# Convert to bool
print('Boolean Tensor:', tensor.bool())
# Convert to int16
print('Short Tensor(int16):', tensor.short())
# Convert to int64
print('Long Tensor(int64):', tensor.long())
# Convert to float32
print('Float Tensor(float32):', tensor.float())
# Convert to float64
print('Double Tensor(float64):', tensor.double())

Tensor:
 tensor([0, 1, 2, 3])
Boolean Tensor: tensor([False,  True,  True,  True])
Short Tensor(int16): tensor([0, 1, 2, 3], dtype=torch.int16)
Long Tensor(int64): tensor([0, 1, 2, 3])
Float Tensor(float32): tensor([0., 1., 2., 3.])
Double Tensor(float64): tensor([0., 1., 2., 3.], dtype=torch.float64)


### Converting Between NumPy Arrays and Tensors
- PyTorch makes it easy to switch between NumPy arrays and tensors, allowing seamless integration with existing computing workflows.

In [27]:
# Create a NumPy array of zeros
x = np.zeros((4, 4))
print('Original Tensor:', x)

# Convert NumPy array to PyTorch tensor
N_to_P = torch.from_numpy(x)
print('Tensor from NumPy:', N_to_P)

# Convert Tensor to NumPy array
P_to_N = N_to_P.numpy()
print('Converted Back to NumPy Array:', P_to_N)

Original Tensor: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Tensor from NumPy: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)
Converted Back to NumPy Array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Tensor Mathematics and Comparison Operations:
- This section explores essential math operations with PyTorch tensors.
  - Addition & Subtraction - Adds and subtracts two tensors element-wise.
  - Division - Uses true division for precise results.
  - Inplace Operations - Modifies a tensor directly without creating a new one.
  - Exponentiations - Raises each element to a power using pow() or **.
  - Comparison - Checks conditions like x>0 or x<0, returing boolean results.
  - Dot Product - Computes the sum of element-wise multiplications between two tenors.

In [2]:
import torch

# Define two tensors
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])
print("Original of Tensor x:", x)
print("Original of Tensor y:", y)

# Addition
add = x + y 
print('Addition:', add)

# Subtracts
sub = x - y
print('Subtraction:', sub)

# Multiplication
mul = x*y
print('Multiplication:', mul)

# Division
div = torch.true_divide(x, y)
print('Division:', div)

# Inplace operations
t = torch.ones(3)
print('Before inplace addition:', t)
t.add_(x)
print('After Inplace Addition:', t)
t = t + x
print('After second inplace addition:', t)

# Exponentiation
z = x.pow(2)
print('Exponentiation (pow):', z)
z = x**2
print('Exponentiation (**):', z)

# Comparisons
z = x > 0
print('x > 0:', z)
z = x < 0
print('x < 0:', z)

# Dot product
z = torch.dot(x, y)
print('Dot Product:', z)

Original of Tensor x: tensor([1, 2, 3])
Original of Tensor y: tensor([9, 8, 7])
Addition: tensor([10, 10, 10])
Subtraction: tensor([-8, -6, -4])
Multiplication: tensor([ 9, 16, 21])
Division: tensor([0.1111, 0.2500, 0.4286])
Before inplace addition: tensor([1., 1., 1.])
After Inplace Addition: tensor([2., 3., 4.])
After second inplace addition: tensor([3., 5., 7.])
Exponentiation (pow): tensor([1, 4, 9])
Exponentiation (**): tensor([1, 4, 9])
x > 0: tensor([True, True, True])
x < 0: tensor([False, False, False])
Dot Product: tensor(46)


### Matrix Multiplication and Batch Operations:
- Matrix operations are at the heart of deep learning. Let's find out different ways to perform multiplication.
  - Matrix Multiplication - Uses @ or torch.mm() to perform standard matrix multiplication.
  - Matrix Exponentiation - Raises a square matrix to a power using matrix_power(n).
  - Element-wise Multiplication - Uses torch.mul() or * for elements-wise multiplication.
  - Batch Matrix Multiplication - Uses torch.bmm() to multiply batches of matrices efficiently.

In [5]:
import torch

x1 = torch.tensor([[1, 2, 3]])
x2 = torch.tensor([[9, 8, 7]])

# Matrix multiplication using @ operator and torch.mm
z = x1 @ torch.t(x2)
print('Matrix Multiplication (@ operator):', z)
z = torch.mm(x1, torch.t(x2))
print('Matrix Multiplication (torch.mm):\n', z)
z = x1.mm(torch.t(x2))
print('Matrix Multiplication (mm):\n', z)

# Matrix exponentiation: multiplying a matrix with itself 3 times
matrix_exp = torch.rand(5, 5)
print('Matrix multiplied 3 times:\n', matrix_exp @ matrix_exp @ matrix_exp)
print('Matrix power 3:\n', matrix_exp.matrix_power(3))

# Element-wise multiplication
z = torch.mul(x, y)
print('Element-wise Multiplication:', z)
z = x * y
print('Element-wise Mulitplication (alternative):', z)

# Batch matrix multiplication
z = torch.mul(x, y)
print('Element-wise Multiplication:', z)
z = x * y
print('Element-wise Multiplication (alternative):', z)

Matrix Multiplication (@ operator): tensor([[46]])
Matrix Multiplication (torch.mm):
 tensor([[46]])
Matrix Multiplication (mm):
 tensor([[46]])
Matrix multiplied 3 times:
 tensor([[2.7703, 1.4174, 1.9260, 3.0814, 2.6754],
        [4.0568, 2.0518, 2.8006, 4.4113, 3.9195],
        [4.3763, 2.3692, 3.2271, 4.8066, 4.5303],
        [3.8904, 2.0234, 2.7478, 4.3445, 3.8227],
        [4.5124, 2.4151, 3.2848, 4.9649, 4.6200]])
Matrix power 3:
 tensor([[2.7703, 1.4174, 1.9260, 3.0814, 2.6754],
        [4.0568, 2.0518, 2.8006, 4.4113, 3.9195],
        [4.3763, 2.3692, 3.2271, 4.8066, 4.5303],
        [3.8904, 2.0234, 2.7478, 4.3445, 3.8227],
        [4.5124, 2.4151, 3.2848, 4.9649, 4.6200]])
Element-wise Multiplication: tensor([ 9, 16, 21])
Element-wise Mulitplication (alternative): tensor([ 9, 16, 21])
Element-wise Multiplication: tensor([ 9, 16, 21])
Element-wise Multiplication (alternative): tensor([ 9, 16, 21])


### Broadcasting and Other Useful Operations:
- Broadcasting allows arithmetic operations on tensors of different shapes.
- This section also demonstrates additional useful functions.
  - Broadcasting - Automatically expands smaller tensors to match larger ones in operations.
  - Summation - torch.sum(x, dim=0) computes sum along a specific dimension.
  - Min/Max Values - torch.max() and torch.min() return the highest and lowest values along the dimension.
  - Absolute Values - torch.abs(x) gets the element-wise absolute values.
  - Argmax/Argmin - torch.argmax() and torch.argmin() return the index of max/min values.
  - Mean Calculation - torch.mean(x.float(), dim=0) computes the mean (ensuring float dtype).
  - Element-wise Comparison - torch.eq(x,y) checks equality between two tensors.
  - Sorting - torch.sort(y, dim=0) sorts tensor elements and returns indices.
  - Clamping - torch.clamp(x, min=0) restricts values within a range.
  - Boolean Operations - torch.any(x_bool) checks if any value is True, torch.all(x_bool) checks if all are True.

In [25]:
import torch

# Define tensor
x1 = torch.rand(5, 5)
x2 = torch.rand(5)
print('x1 Tensor:\n', x1)
print('x2 Tensor:\n', x2)

# Broadcasting Operations
print('x1-x2:\n', x1-x2)
print('x1 raised to the power of x2:\n', x1 ** x2)

# Summation
sum_x = torch.sum(x, dim=0)
print('Summation:\n', sum_x)

# Maximum and Minimum
value, indices = torch.max(x, dim=0)
print('Maximum:\n', value, indices)
value, indices = torch.min(x, dim=0)
print('Minimum:\n', value, indices)

# Absolute Values
abs_x = torch.abs(x)
print('Absolute:\n', abs_x)

# Argmax and Argmin values
arg_max = torch.argmax(x, dim=0)
print('Arg Max:\n', arg_max)
arg_min = torch.argmin(x, dim=0)
print('Min Arg:\n', arg_min)

# Mean and Converted to float datatype
mean = torch.mean(x.float(), dim=0)
print('Mean (Converted into float):\n', mean)

# Element-wise Comparsion
EWC = torch.eq(x, y)
print('Element-wise Comparsion:\n', EWC)

# Sorting
sort = torch.sort(y, dim=0, descending=False)
print('Sorting:\n', sort) 

# Clamping values
clamp = torch.clamp(x, min=0)
print('Clamping :\n', clamp)

# Boolean Operations
x_bool = torch.tensor([1, 0, 1, 1 ,0], dtype=torch.bool)
print('Check If Any Value is True:\n', torch.any(x_bool))
print('Check If All Values are True:\n', torch.all(x_bool))

x1 Tensor:
 tensor([[0.1560, 0.6011, 0.4744, 0.8213, 0.1966],
        [0.5637, 0.5654, 0.3577, 0.8722, 0.6939],
        [0.5776, 0.1514, 0.4505, 0.2407, 0.6078],
        [0.4737, 0.1212, 0.9197, 0.0544, 0.8385],
        [0.2610, 0.7419, 0.7982, 0.5026, 0.9393]])
x2 Tensor:
 tensor([0.8737, 0.3888, 0.8337, 0.4574, 0.4545])
x1-x2:
 tensor([[-0.7178,  0.2123, -0.3593,  0.3639, -0.2579],
        [-0.3100,  0.1766, -0.4760,  0.4148,  0.2394],
        [-0.2961, -0.2374, -0.3832, -0.2167,  0.1533],
        [-0.4000, -0.2677,  0.0860, -0.4030,  0.3839],
        [-0.6128,  0.3531, -0.0355,  0.0452,  0.4847]])
x1 raised to the power of x2:
 tensor([[0.1972, 0.8204, 0.5370, 0.9139, 0.4774],
        [0.6060, 0.8012, 0.4244, 0.9394, 0.8470],
        [0.6191, 0.4799, 0.5144, 0.5213, 0.7975],
        [0.5206, 0.4401, 0.9326, 0.2639, 0.9230],
        [0.3092, 0.8904, 0.8287, 0.7300, 0.9719]])
Summation:
 tensor(6)
Maximum:
 tensor(3) tensor(2)
Minimum:
 tensor(1) tensor(0)
Absolute:
 tensor([1, 2, 3])

### Tensor Indexing:
- Access and modify tensor elements using indexing, slicing, and advanced indexing.
  - Accessing Rows & Columns - Use x[row,:] for a row and x[:, col] for a column.
  - Slicing - x[row, start:end] extracts a portion of a row.
  - Modifying Elements - Directly assign values using x[row, col] = value.
  - Fancy Indexing - Use a list of indices to select multiple elements at once.
  - Conditional Indexing - Extract elements using conditions like (x<2) | (x>8).
  - Finding Even Number - Use x.remainder(2) == 0 to filter even values.
  - Conditional Selection with torch.where() - Chooses values based on a condition.

In [34]:
import torch

# Create a random tensor with shape (batch_size, features)
batch_size = 10
features = 10
x = torch.rand((batch_size, features))

# Access the first row
print('First row of Tensor:', x[0, :])

# Access the second column
print('Second column of Tensor:', x[:1])

# Modify a specific element (set first element to 100)
x[0, 0] = 100

# Fancy indexing example
x = torch.arange(10)
indices = [2, 5, 8]
print('Fancy indexing result:', x[indices])

# conditional indexing
x1 = torch.arange(10)
print('Elements where x1 < 2 or x1 > 8:', x1[(x1 < 2) | (x1 > 2)])

# Finding Even number using x.remainder(2)
print('Even number in x1:', x1[x1.remainder(2) == 0])

# Using torch.where to select values based on a condition
print('Using torch.where:', torch.where(x1 > 5, x1, x1 * 2))

First row of Tensor: tensor([0.9084, 0.3931, 0.6936, 0.5728, 0.1581, 0.9039, 0.8750, 0.8981, 0.6394,
        0.4696])
Second column of Tensor: tensor([[0.9084, 0.3931, 0.6936, 0.5728, 0.1581, 0.9039, 0.8750, 0.8981, 0.6394,
         0.4696]])
Fancy indexing result: tensor([2, 5, 8])
Elements where x1 < 2 or x1 > 8: tensor([0, 1, 3, 4, 5, 6, 7, 8, 9])
Even number in x1: tensor([0, 2, 4, 6, 8])
Using torch.where: tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


### Tensor Reshaping:
- Learn how to reshape tensors, concatenate them, and change the order of dimensions.
  - Reshape with view() & reshape() - Change tensor shape without altering data.
  - Transpose & Flattern - .t() transposes, .contiguous().view(-1) flattens.
  - Concatenation - torch.cat([x1, x2], dim=0/1) merges tensors along rows/columns.
  - Flattening - .view(-1) converts a tensor into a 1D array.
  - Batch Reshaping - .view(batch, -1) keeps batch size while reshaping.
  - Permute Dimensions - .permute(0, 2, 1) reorders dimensions efficiently.
  - Unsqueeze for New Dimensions - .unsqueeze(dim) adds singleton dimensions.

In [42]:
import torch

# Define a tensor
x = torch.arange(9)
print('x:\n', x)

# Reshape a tensor using view and reshape
x_3x3 = x.view(3, 3)
print('Reshaped to 3x3 using view:\n', x_3x3)
x_3x3 = x.reshape(3, 3)
print('Reshaped to 3x3 using reshape:\n', x_3x3)

# Transpose and Flatten the tensor
y = x_3x3.t()
print('Transpose tensor:', y)
z = y.contiguous().view(9)
print('Flattened tensor:\n', z)

# Flatten the tensor using view(-1)
z = x.view(-1)
print('Flattened tensor shape:\n', z)

# Batch Reshaping
batch = 64
x = torch.rand(batch, 2, 5)
print('Reshaped to (batch, -1):', x.view(batch, -1).shape)

# Permute dimension
z = x.permute(0, 2, 1)
print('Permuted tensor shape:', z.shape)

# Unsqueeze for Dimension
x = torch.arange(10)
print('Original of x:', x)
print('x unsqueezed at dim 0:', x.unsqueeze(0).shape, x.unsqueeze(0))
print('x unsqueezed at dim 1:', x.unsqueeze(1).shape, x.unsqueeze(1))

x:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
Reshaped to 3x3 using view:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Reshaped to 3x3 using reshape:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Transpose tensor: tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
Flattened tensor:
 tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
Flattened tensor shape:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
Reshaped to (batch, -1): torch.Size([64, 10])
Permuted tensor shape: torch.Size([64, 5, 2])
Original of x: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x unsqueezed at dim 0: torch.Size([1, 10]) tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
x unsqueezed at dim 1: torch.Size([10, 1]) tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
