### What is TensorFlow:
- TensorFlow is a open-source machine learning framework developed by Google.
- It is written in Python, making it accessible and easy to understand.
- It is designed to build and train machine learning and deep learning models.
  1. It is highly scalable for both research and production.
  2. It supports CPUs, GPUs and TPUs for faster computation.
  3. It provides built-in tools for visualization and debugging.
  4. It works seamlessy with other AI Frameworks and libraries.

### Difference between TensorFlow and Keras:
#### TensorFlow:
- Tensorhigh-performanceFlow is written in C++, CUDA, Python.
- TensorFlow is used for large datasets and high performance models.
- TensorFlow is a framework that offers both high and low level APIs.
- TensorFlow is used for high performance models.
- TensorFlow has a complex architecture and not easy to use.
- In TensorFlow performing debugging leads to complexities.
- TensorFlow was developed by the Google Brain Team.

#### Keras:
- Keras is wriiten in Python.
- Keras is used for small datasets.
- Keras is high-level APIs.
- Keras is used for low-performance models.
- Keras has a simple architecture and easy to use.
- In Keras framework, there is only minimal requirements for debugging the simple networks.
- Keras was develpoed by Franscois Chollet while he was working on the part of the research effort of project ONEIROS.

### Basic Concepts of TensorFlow:
#### What is Tensors:
- Tensors are multidimensional arrays, fundamental to TensorFlow's operations and computations.
- Understanding the key concepts like tensor shape, size, rank, dimension is crucial for effectively using TensorFlow in machine learning projects.
#### What is Tensor Shape?
- Tensor refers to the layout or structure of a tensor.
- Which defines the number of dimensions and size of each dimension in the tensor.
- It describes how many elements are along each axis of the tensor.
#### What is Tensor Size?
- Tensor refers to the total number of elements ina tensor.
- It is the product of all the dimensions(sizes) of the tensor.

In [9]:
import tensorflow as tf

# Create a tensor
tensor = tf.constant([[1,2,3],[4,5,6]])

# Get the shape of the tensor.
shape = tensor.shape
print('Tensor:', tensor)
print('Tensor shape:', shape)

# Get the size of the tensor.
size = tf.size(tensor)
print('Tensor size:', size)

Tensor: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor shape: (2, 3)
Tensor size: tf.Tensor(6, shape=(), dtype=int32)


#### What is Tensor Rank?
- It indicates number of dimensions present in a tensor.
- Here's a brief overview of tensor rank:
  - Rank 0: Scalers. Tensors of rank 0 represent single values.
  - Rank 1: Vectors. Tensors of rank 1 have one dimensional and represent arrays of values.
  - Rank 2: Matrices. Tensors of rank 2 have two dimensions and represent 2D arrays of values.
  - Rank 3 and above: Tensors of rank 3 or higher have three or more dimensions and represent higher-dimensional arrays of values.

In [11]:
import tensorflow as tf
scaler = tf.constant(3)
vector = tf.constant([1,2,3])
matrix = tf.constant([[1,2,3],[4,5,6]])
tensor_3d = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])

rank_scaler = tf.rank(scaler)
rank_vector = tf.rank(vector)
rank_matrix = tf.rank(matrix)
rank_tensor_3d = tf.rank(tensor_3d)

print('Rank of scaler:',rank_scaler.numpy())
print('Rank of vector:',rank_vector.numpy())
print('Rank of matrix:',rank_matrix.numpy())
print('Rank of 3D tensor:',rank_tensor_3d.numpy())

Rank of scaler: 0
Rank of vector: 1
Rank of matrix: 2
Rank of 3D tensor: 3


#### What is Tensor Dimension?
- Tensor dimension refers to the length along a particular axis of a tensor.

In [12]:
import tensorflow as tf
tensor = tf.constant([[1,2,3],[4,5,6]])
shape = tensor.shape
dim1_length = shape[0]
dim2_length = shape[1]

print('Tensor shape:', shape)
print('Length of first dimension:', dim1_length)
print('Length of second dimension:', dim2_length)

Tensor shape: (2, 3)
Length of first dimension: 2
Length of second dimension: 3


#### What is Tensor Slicing?
- It refers to the extracting specific subsets of data from a tensor along one or more dimensions.
- This operation takes three arguments.
  1. The main ingredient: the tensor you want to slice.
  2. Starting point [included]: where you want to begin the slice.
  3. Ending point[excluded]: how much you want to slice.

In [16]:
import tensorflow as tf
tensor1 = tf.constant([1,2,3,4,5,6,7,8,9])
tensor1
tensor_slice1 = tf.slice(tensor1,begin=[1], size=[4])
print(tensor_slice1)

import tensorflow as tf
t2 = tf.constant([[0,1,2],[3,4,5],[6,7,8]])
t2
# Get the first row
first_row = tf.slice(t2, [0, 0], [1, tf.shape(t2)[1]])
print('First Row:\n', first_row)

# Get the second column
second_column = tf.slice(t2, [0, 1], [tf.shape(t2)[0], 1])
print('\nSecond Column:\n', second_column)

# Get the second and third columns
second_third_columns = tf.slice(t2, [0, 1], [tf.shape(t2)[0], 2])
print('\nSecond & Third Columns:\n', second_third_columns)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
First Row:
 tf.Tensor([[0 1 2]], shape=(1, 3), dtype=int32)

Second Column:
 tf.Tensor(
[[1]
 [4]
 [7]], shape=(3, 1), dtype=int32)

Second & Third Columns:
 tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)


#### what is Extracting Tensors?
- Extracting tensors let you grab specific elements or chunks of your data.
- It takes two arguments.
  1. The treasure chest: your main tensor filled with data.
  2. The treasure map: a list of indices telling you which goodies to grab.
- Advanced Picking - For even more granular control, use tf.gather_nd.
- It takes:
  1. The treasure chest: same as before.
  2. A multi-layered treasure map: each inner list specifies the location of your desired element.

In [19]:
import tensorflow as tf
t1 = tf.constant([0,1,2,3,4,5,6,7])
t1
t1_gather = tf.gather(t1, indices=[0,3,6])
print(t1_gather)


import tensorflow as tf
t2 = tf.constant([[0,1,2],[3,4,5],[6,7,8]])
t2
Indices = tf.constant([1,0])
r = tf.gather(t2, indices=Indices, axis=0)
print('Along Row:\n',r)
c = tf.gather(t2, indices=Indices, axis=1)
print('Along Col:\n',c)

tf.Tensor([0 3 6], shape=(3,), dtype=int32)
Along Row:
 tf.Tensor(
[[3 4 5]
 [0 1 2]], shape=(2, 3), dtype=int32)
Along Col:
 tf.Tensor(
[[1 0]
 [4 3]
 [7 6]], shape=(3, 2), dtype=int32)


In [21]:
import tensorflow as tf
t3 = tf.constant([[[1, 3, 5, 7],
                   [9, 11, 13, 15]],
                  [[17, 19, 21, 23],
                   [25, 27, 29, 31]]])
t3
Indices = [[0,0,0],[1,1,1],[1,0,3]]
special_picks = tf.gather_nd(t3, indices=Indices, batch_dims=0)
print(special_picks)
print('The value at index t3[0, 0, 0] :',t3[Indices[0]])
print('The value at index t3[1, 1, 1] :',t3[Indices[1]])
print('The value at index t3[1, 0, 3] :',t3[Indices[2]])

tf.Tensor([ 1 27 23], shape=(3,), dtype=int32)
The value at index t3[0, 0, 0] : tf.Tensor(1, shape=(), dtype=int32)
The value at index t3[1, 1, 1] : tf.Tensor(27, shape=(), dtype=int32)
The value at index t3[1, 0, 3] : tf.Tensor(23, shape=(), dtype=int32)


#### What is Inserting Tensor?
- Insering in TensorFlow lets you plant specific values or chunks of data.
- It takes three arguments:
  1. planting map: a list of indices telling you where to put the seeds(elements).
  2. seed bag: the values you want to insert.
  3. Garden size: the overall shape of your final "planted" tensor.
- Advanced Inserting:
- tf.scatter_nd works for multi-dimensional gardens tool.

In [24]:
import tensorflow as tf
t4 = tf.zeros_like(tf.constant([0,0,0,0,0,0,0,0]))
t4

Index = [[1],[3],[6]]
values = [10, 20, 30]
t4 = tf.scatter_nd(indices=Index,
                   updates=values,
                   shape=[8])
print(t4)


tf.Tensor([ 0 10  0 20  0  0 30  0], shape=(8,), dtype=int32)


In [27]:
import tensorflow as tf
t5 = tf.zeros(shape=(4,5))
t5

Index = [[0,0],[1,1],[2,2]]
values = [100,200,300]
t5 = tf.scatter_nd(indices=Index,
                  updates=values,
                  shape=t5.shape)
print(t5)

tf.Tensor(
[[100   0   0   0   0]
 [  0 200   0   0   0]
 [  0   0 300   0   0]
 [  0   0   0   0   0]], shape=(4, 5), dtype=int32)


#### What is Reshaping Tensor?
- Tensor reshaping is the process of reshaping the order and total number of elements in tensors while only the shape is being changed.
- tf.reshape(tensor, shape, name=None) - function is used to reshape tensors.
- It takes three arguments:
  - tensor: The tensor which you want to change the shape of.
  - shape: The shape of the output.
  - The name is optional parameter that would allow you to set a name for the operation.
- Using the special value -1 as shape:
- tf.reshape(t,[-1]) - to reshape the input tensor t.
- The [-1] argument indicates the reshaped to 1D tensor.
#### DataTypes in Tensorflow:
- A list of some commonly used data types in TensorFlow:
  1. tf.float16 - 16-bit floating point.
  2. tf.float32 - 32-bit floating point.
  3. tf.float34 - 64-bit floating point.
  4. tf.int8 - 8-bit integer.
  5. tf.int16 - 16-bit integer.
  6. tf.int32 - 32-bit integer.
  7. tf.int64 - 64-bit integer.
  8. tf.uint8 - 8-bit unsigned integer.
  9. tf.bool - Boolean.
  10. tf.string - String.


In [43]:
import tensorflow as tf
t1 = tf.constant([[1,2,3],[4,5,6]])
t1
print('Tensor:',t1)
print('\n Shape of Tensor:', tf.shape(t1).numpy())

# Reshaping to 1D.
t2 = tf.reshape(t1 ,[6])
print('\nTensor:',t2)
print('Shape of Tensor:',tf.shape(t2).numpy())

# Reshaping to 2D
t3 = tf.reshape(t1, [1,6])
print('\nTensor:',t3)
print('Shape of Tensor:',tf.shape(t3).numpy())

# Using special value -1 as shape.
t4 = tf.reshape(t1, [-1])
print('\nReshaped Result:',t4)
print('\nOriginal Tensor shape:',tf.shape(t1))
print('Flattened Tensor Shape:',tf.shape(t4))

Tensor: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

 Shape of Tensor: [2 3]

Tensor: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
Shape of Tensor: [6]

Tensor: tf.Tensor([[1 2 3 4 5 6]], shape=(1, 6), dtype=int32)
Shape of Tensor: [1 6]

Reshaped Result: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)

Original Tensor shape: tf.Tensor([2 3], shape=(2,), dtype=int32)
Flattened Tensor Shape: tf.Tensor([6], shape=(1,), dtype=int32)


#### what is Transpose Tensors?
- It is used to changes the arrangement of dimensions.
- Here, the perm argument [1,0] indicates that the rows and columns should be swapped, resulting in a transposed tensor.

In [40]:
import tensorflow as tf
t1 = tf.constant([[1,2,3],[4,5,6]])
print('Original Tensor:')
print(t1)

# Reshaping to a [3,2].
t2 = tf.reshape(t1,[3,2])
print('\n Reshaped Tensor:')
print(t2)

# Transpose the elements.
t3 = tf.transpose(t1, perm=[1,0])
print('\nTranspose Tensor:')
print(t3)

Original Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

 Reshaped Tensor:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

Transpose Tensor:
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


### What is Tensor Broadcasting?
- Tensor broadcasting is a concept of array processing libraries like TensorFlow and NumPy, It allows for implict element-wise operations between arrays of different shapes.
- tf.expand_dims(input, axis,name) can be used to add the dimension of one to the Tensorflow on axis.

In [57]:
import tensorflow as tf
t1 = tf.constant([[1,2,3],[4,5,6]]) # shape:(2,3), rank 2.
t2 = tf.constant([[7,8,9]]) # shape:(1,3), rank 2.
t3 = t1 + t2
print(t3)

import tensorflow as tf
t4 = tf.constant([[1,2,3],[4,5,6]]) # shape:(2,3), rank 2.
t5 = tf.constant([20, 40, 50]) # shape:(3,), rank 1.
t6 = t4 + t5
print('\n')
print(t6)

import tensorflow as tf
t7 = tf.constant([[1,2,3],[4,5,6]]) # shape:(2,3), rank 2.
t8 = tf.constant(5) # shape:(), rank 0.
t9 = t7 + t8
print('\n')
print(t9)

import tensorflow as tf
t10 = tf.constant([[[1,2],[3,4],[5,6]],
                   [[7,8],[9,10],[11,12]]]) # shape:(2,3,2), rank 3.
t11 = tf.constant([[1,2,3],[4,5,6]]) # shape:(2,3), rank 2.
broadcasted_t12 = tf.expand_dims(t1, axis=-1)
t13 = t10 + broadcasted_t12 
print('\n')
print(t13)

tf.Tensor(
[[ 8 10 12]
 [11 13 15]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[21 42 53]
 [24 45 56]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[ 6  7  8]
 [ 9 10 11]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[[ 2  3]
  [ 5  6]
  [ 8  9]]

 [[11 12]
  [14 15]
  [17 18]]], shape=(2, 3, 2), dtype=int32)


### What is Ragged Tensors?
- Ragged tensors are a fundamental data structure in Tensorflow, especially in scenarios where data doesn't conform to fixed shapes, such as sequences of varying lengths or nested structures.
- Ragged tensors posses several distinct features:
  1. Rank - Similat to conventional tensors, ragged tensors have a rank, denoting the number of axes they contain.
  2. Values - Ragged tensors can contain scalers, matrics or even other ragged tensors, providing additional versatility of data representation.
  3. Shape - The shape of a ragged tensors isn't fixed tuple of dimensions.
#### Why use Ragged Tensors:
- Where data exhibits irregulaities and fails to adhere to fixed shapes. Their versatility becomes apparent in various deomains.
  1. NLP - senetnces and paragraph have different lengths. Ragged handle this irregularity perfectly, making them ideal for tasks like sentiment analysis and machine translation.
  2. Time series - Sensors reading or financial data may have missing entries or be collected at irregular intervals. Ragged tensors effortlessly manage these inconsistencies.
### Constructing Ragged Tensors
#### 1. Using tf.ragged.constant():
- We use this to create a ragged tensor from nested Python lists.

In [59]:
import tensorflow as tf
t1 = tf.ragged.constant([[1,2],[3,4,5],[6]])
print(t1)

<tf.RaggedTensor [[1, 2], [3, 4, 5], [6]]>


#### 2. Using tf.RaggedTensor.from_value_rowids:
1. Values Tensor - Create a flat tensor containing all the words.
2. Value Rows Tensor - This tensor tell us which row(sentence) each word belongs to. It should have same length as the value tensor.

In [60]:
import tensorflow as tf
words = [3,4,5,6,7,9]
row_ids = [0,0,0,2,2,3]
t1 = tf.RaggedTensor.from_value_rowids(values = words, value_rowids=row_ids)
print(t1)

<tf.RaggedTensor [[3, 4, 5], [], [6, 7], [9]]>


#### 3. Using tf.RaggedTensor.from_row_lengths:
- This is constant tensor containing information about the number of elements in each row of the desired RaggedTensor.
- Below [2,2,2,2] specifies that we want four rows, each with two elements.

In [61]:
import tensorflow as tf
values = tf.constant([1,2,3,0,4,0,5,6])
row_lengths = tf.constant([2,2,2,2])
t1 = tf.RaggedTensor.from_row_lengths(values, row_lengths)
print(t1)

<tf.RaggedTensor [[1, 2],
 [3, 0],
 [4, 0],
 [5, 6]]>


#### 4. Using tf.RaggedTensor.from_row_splits:
- This is a constant tensor, but instead of lengths, it contains information about where each row starts in the values tensor.
- Below [0,2,4,6,8] indicates that the starting index for each row: 0(first element), 2(third element), 4(fifth element), 6(seventh element).

In [62]:
import tensorflow as tf
values = tf.constant([1,2,3,0,4,0,5,6])
row_splits = tf.constant([0,2,4,6,8])
t1 = tf.RaggedTensor.from_row_splits(values, row_splits)
print(t1)

<tf.RaggedTensor [[1, 2],
 [3, 0],
 [4, 0],
 [5, 6]]>


### Operations on Ragged Tensors:
- Ragged tensors support various operations similar to regular tensors in TensorFlow.
  - tf.add() - To perform element-wise addition between ragged tensors.
  - tf.reduce_mean - To calculate mean.
  - tf.concat - To concatenating ragged tensors along a specified axis.
  - .bounding_shape()- Getting shapes using shape attributes.

In [64]:
import tensorflow as tf
ragg1 = tf.ragged.constant([[1,2],[3,4]])
ragg2 = tf.ragged.constant([[5,6],[7,8]])

add_ragged = tf.add(ragg1,ragg2)
mean_value = tf.reduce_mean(add_ragged)
concat = tf.concat([ragg1,ragg2],axis=0)
rag_shape = ragg1.bounding_shape()

print("Added Ragged Tensor:")
print(add_ragged)
print("Mean Value of Ragged Tensor:", mean_value.numpy())
print("Concatenated Ragged Tensor:")
print(concat)
print("Shapes of Elements Inside the Ragged Tensor:", rag_shape)

Added Ragged Tensor:
<tf.RaggedTensor [[6, 8],
 [10, 12]]>
Mean Value of Ragged Tensor: 9.0
Concatenated Ragged Tensor:
<tf.RaggedTensor [[1, 2],
 [3, 4],
 [5, 6],
 [7, 8]]>
Shapes of Elements Inside the Ragged Tensor: tf.Tensor([2 2], shape=(2,), dtype=int64)
