### What is Sparse Tensors?
- Tensors are the building blocks of mathematical operations on the data.
- However, sometimes, tensors can have majority of values as zero. Such a tensor with a lot of zero values is called as sparse tensor.
- Sparse tensors are mostly encountered in the fields of computer vision and natural language processing.These can be pretty overwhelming at times.
#### How to crete Sparse Tensors in TensorFlow?
- There are two ways to create a sparse tensor.
#### 1. By directly specifying Indices and Values:
- tf.sparse.SparseTensor object - you can represent sparse tensor.
- when creating a sparse tensor, you need to specify the following three components:
  - Values: These are the non-zero values. represented in 1D tensor.
  - Indices: These are the indices of the non-zero values in the tensor, represented in 2D tensor.
  - Dense Shape: It specifies the overall shape of the tensor in 1D tensor.


In [2]:
import tensorflow as tf

# Define non-zero values and their indices
Values = tf.constant([41,30], dtype=tf.int32)
Indices = tf.constant([[1,2] ,[3,3]], dtype=tf.int64)
Dense_shape = tf.constant([4,8], dtype=tf.int64)

# Create a sparse tensor
sparse_tensor = tf.sparse.SparseTensor(indices=Indices, values=Values, dense_shape=Dense_shape)

# Print the sparse tensor
print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[1 2]
 [3 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([41 30], shape=(2,), dtype=int32), dense_shape=tf.Tensor([4 8], shape=(2,), dtype=int64))


#### 2. Creating from Dense Tensor:
- tf.sparse.from_dense - Method can be used to convert dense to sparse tensor.
- In case you are working on a large dataset, basically comprising all tensors.
- However, you notice that most of the values in the tensor are zero.

In [6]:
import tensorflow as tf

# Create a dense tensor
dense_tensor = tf.constant([[1, 0, 0], [0, 0, 2], [0, 3, 0]], dtype=tf.float32)

# Convert the dense tensor to a sparse tensor
sparse_tensor = tf.sparse.from_dense(dense_tensor)

print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]
 [2 1]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))


### How to manipulate sparse tensors?
- You can manipulate sparse tensors in multiple ways using different methods.
- There is a package called tf.sparse package which consists of all the tools and methods that allows us to perform arithmetic manipulations, matrix multiplications, concatenation, and more.
#### 1. Arithmetic Manipulations:
- Traditional arithmetic manipulations are not directly applicable on sparse tensors.
- Therefore, to add sparse tensors of same shape we use -
  - tf.sparse.add function.

In [5]:
import tensorflow as tf

# Create two sparse tensors
sparse_tensor1 = tf.sparse.SparseTensor(indices = [[0,3], [2,4]], 
                                        values=[10, 20], dense_shape=[5,5])
sparse_tensor2 = tf.sparse.SparseTensor(indices = [[1,2], [4,2]],
                                        values=[30,40], dense_shape=[5,5])

# Add sparse tensors
result_sparse_tensor = tf.sparse.add(sparse_tensor1, sparse_tensor2)

# print the result
print(result_sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 3]
 [1 2]
 [2 4]
 [4 2]], shape=(4, 2), dtype=int64), values=tf.Tensor([10 30 20 40], shape=(4,), dtype=int32), dense_shape=tf.Tensor([5 5], shape=(2,), dtype=int64))


#### 2. Sparse_Dense Matrix Multiplication:
- If you want to multiply a sparse tensor and a dense tensor you can use -
  - tf.sparse.sparse_dense_matmul

In [10]:
import tensorflow as tf

# Define a sparse tensor
sparse_indices = tf.constant([[0, 2], [1, 0], [1, 2], [2, 1]], dtype=tf.int64)
sparse_values = tf.constant([1.0, 2.0, 3.0, 4.0], dtype=tf.float32)
sparse_shape = tf.constant([3, 3], dtype=tf.int64)

sparse_tensor = tf.sparse.SparseTensor(indices=sparse_indices, values=sparse_values, dense_shape=sparse_shape)

# Define a dense matrix
dense_matrix = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]], dtype=tf.float32)

# Perform sparse-dense matrix multiplication
result_dense_matrix = tf.sparse.sparse_dense_matmul(sparse_tensor, dense_matrix)

# Print the result

print(result_dense_matrix)

tf.Tensor(
[[ 7.  8.  9.]
 [23. 28. 33.]
 [16. 20. 24.]], shape=(3, 3), dtype=float32)


#### 3. Concatenation:
- In order to concatenate two sparse tensors, you can use -
  - tf.sparse.concat

In [11]:
import tensorflow as tf

# Create two sparse tensors
sparse_indices1 = tf.constant([[0, 1], [1, 0], [2, 2]], dtype=tf.int64)
sparse_values1 = tf.constant([9, 2, 5], dtype=tf.int32)
sparse_shape1 = tf.constant([3, 3], dtype=tf.int64)

sparse_tensor1 = tf.sparse.SparseTensor(indices=sparse_indices1, values=sparse_values1, dense_shape=sparse_shape1)

sparse_indices2 = tf.constant([[3, 1], [4, 0]], dtype=tf.int64)
sparse_values2 = tf.constant([6, 8], dtype=tf.int32)
sparse_shape2 = tf.constant([5, 3], dtype=tf.int64)

sparse_tensor2 = tf.sparse.SparseTensor(indices=sparse_indices2, values=sparse_values2, dense_shape=sparse_shape2)

# Concatenate sparse tensors vertically
result_sparse_tensor = tf.sparse.concat(axis=0, sp_inputs=[sparse_tensor1, sparse_tensor2])

# print the result
print(result_sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 2]
 [6 1]
 [7 0]], shape=(5, 2), dtype=int64), values=tf.Tensor([9 2 5 6 8], shape=(5,), dtype=int32), dense_shape=tf.Tensor([8 3], shape=(2,), dtype=int64))


#### 4. Slicing: 
- It is very easy to slice a sparse tensor. You need to simpliy need to use -
  - tf.sparse.slice

In [13]:
import tensorflow as tf

# Create a sparse tensor
sparse_indices = tf.constant([[0, 1], [1, 0], [2, 2], [2, 3]], dtype=tf.int64)
sparse_values = tf.constant([7, 14, 12, 11], dtype=tf.int32)
sparse_shape = tf.constant([3, 4], dtype=tf.int64)

sparse_tensor = tf.sparse.SparseTensor(indices=sparse_indices, values=sparse_values, dense_shape=sparse_shape)

# Print the original sparse
print(sparse_tensor)

# Slice the sparse tensor
sliced_sparse_tensor = tf.sparse.slice(sparse_tensor, start=[1, 0], size=[2, 3])

# print the sliced result
print(sliced_sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 2]
 [2 3]], shape=(4, 2), dtype=int64), values=tf.Tensor([ 7 14 12 11], shape=(4,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([14 12], shape=(2,), dtype=int32), dense_shape=tf.Tensor([2 3], shape=(2,), dtype=int64))


#### 5. Elementwise Operations:
- If you want to perform elementwise operations on nonzero values in sparse tensors, you can use -
  - tf.sparse.map_values

In [15]:
import tensorflow as tf

# Create a sparse tensor
sparse_indices = tf.constant([[0, 1], [1, 0], [2, 2], [2, 3]], dtype=tf.int64)
sparse_values = tf.constant([21,11,13, 8], dtype=tf.int32)
sparse_shape = tf.constant([3, 4], dtype=tf.int64)

sparse_tensor = tf.sparse.SparseTensor(indices=sparse_indices, 
                                       values=sparse_values, dense_shape=sparse_shape)

# Define an elementwise operation function
def elementwise_operation(value):
    return value * 2

# Apply elementwise operation to nonzero values
result_sparse_tensor = tf.sparse.map_values(elementwise_operation, sparse_tensor)

# print the result
print(result_sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 2]
 [2 3]], shape=(4, 2), dtype=int64), values=tf.Tensor([42 22 26 16], shape=(4,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


#### Sparse Tensors[ reduce max]:
- Sparse Tensors treat explict zeros values and missing values as the same for most of the operations on -
  - tf.sparse.SparseTensors.
- If you use this, it will not treat missing value as zero. we use -
  - tf.sparse.reduce_max

In [17]:
import tensorflow as tf

# Create a sparse tensor with explicit zeros and missing values
sparse_indices = tf.constant([[0, 0], [1, 1], [2, 2]], dtype=tf.int64)
sparse_values = tf.constant([0.0, 0.0, 3.0], dtype=tf.float32)
sparse_shape = tf.constant([3, 3], dtype=tf.int64)

sparse_tensor = tf.sparse.SparseTensor(indices=sparse_indices, values=sparse_values, dense_shape=sparse_shape)

# Reduce max, treating missing values as zeros
result_max = tf.sparse.reduce_max(sparse_tensor)

# Print the result
print('Result of reduce_max:', result_max.numpy())

Result of reduce_max: 3.0
