### What is Tensor Bitwise operations?
- Tensor bitwise operations in Python involve performing logical operations at the bit level on tensors, which are multi-dimensional arrays widely used inmachine learning and deep learning frameworks like TensorFlow and PyTorch.
### Tensor Bitwise Operations:
#### Bitwise AND Operation:
- tf.bitwise.bitwise_and() - Function is used in the code performs a bitwise AND operation element-wise between two TensorFlow tensors.

In [1]:
import tensorflow as tf

# Define the tensors
tensor1 = tf.constant([5, 3, 8])
tensor2 = tf.constant([9, 8, 7])

result_and = tf.bitwise.bitwise_and(tensor1, tensor2)
print('Bitwise AND Operation:')
print(result_and)

C:\Users\techs\anaconda3\New folder\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


Bitwise AND Operation:
tf.Tensor([1 0 0], shape=(3,), dtype=int32)


#### Bitwise OR Operation:
- tf.bitwise.bitwise_or() - Function is used in the code performs a bitwise OR Operation element-wise between Two TensorFlow tensors.
- tf.bitwise.left_shift() - Function is applied to the result of the bitwise OR operation(result_or).

In [2]:
import tensorflow as tf

# Define the Tensors
t1 = tf.constant([5,3,8])
t2 = tf.constant([7,1,9])
result_or = tf.bitwise.bitwise_or(t1,t2)

result_shift = tf.bitwise.left_shift(result_or, 2)

print('Result of Bitwise OR and shift Operation:')
print(result_shift.numpy())

Result of Bitwise OR and shift Operation:
[28 12 36]


#### Bitwise XOR with Bit Counting:
- tf.bitwise.bitwise_xor() - Function is used in the code performs a bitwise XOR Operation element-wise between two TensorFlow tensors.

In [3]:
import tensorflow as tf

# Define the Tensors
t1 = tf.constant([5,7,3])
t2 = tf.constant([8,6,1])
result_xor = tf.bitwise.bitwise_xor(t1, t2)

count_bits = tf.math.count_nonzero(result_xor, axis=-1)
print('Result of Bitwise XOR and Counting set Bits:')
print(count_bits)

Result of Bitwise XOR and Counting set Bits:
tf.Tensor(3, shape=(), dtype=int64)


#### Bitwise Invert Operation:
- tf.bitwise.invert() - computes the complement of that element, swapping each 0 bit to 1 and each 1 bit to 0, regardless of the datatype of the tensor.

In [7]:
import tensorflow as tf

# Create a sample tensor
tensor = tf.constant([1, 2, 3, 4, 5], dtype=tf.uint8)

# Invert the bits of the tensor
inverted_tensor = tf.bitwise.invert(tensor)

# Print the original and inverted tensors
print("Original tensor:", tensor.numpy())
print("Inverted tensor:", inverted_tensor.numpy())

Original tensor: [1 2 3 4 5]
Inverted tensor: [254 253 252 251 250]


#### Left and right shift operations:
- tf.bitwise.left_shift() - This operation shifts the bits of each element in the tensor to the left by a specified no of positions, padding the right side with zeros.
- tf.bitwise.right_shift() - This operation shifts the bits of each element in the tensor to the right by a specified no of positions, padding the right side with zeros.

In [10]:
import tensorflow as tf

# Define the tensor
t1 = tf.constant([5,3,7])

result_left_shift = tf.bitwise.left_shift(t1,1)
print('Result of Left Shift Operation:')
print(result_left_shift.numpy())

result_right_shift = tf.bitwise.right_shift(t1,1)
print('Result of Right Shift Operation:')
print(result_right_shift.numpy())

Result of Left Shift Operation:
[10  6 14]
Result of Right Shift Operation:
[2 1 3]
