### Mathematical Operations with Tensors:
- The numerical operations include addition, subtarction, multiplication, dividion, and more.
- Here, tf.constant() - is used for defining tensors.
  - tf.add() - is used to perform element-wise addition on tensors a and b.
  - tf.subtract() - is used for element-wise subtraction.
  - tf.multiply() - performs element-wise multiplication.
  - tf.divide() - is used for element-wise division.

In [2]:
import tensorflow as tf
a = tf.constant([3, 3, 3])
b = tf.constant([2, 2, 2])
sum_result = tf.add(a, b)
dif_result = tf.subtract(a, b)
div_result = tf.divide(a, b)
mul_result = tf.multiply(a, b)

print('Sum of Tensors:', sum_result)
print('Difference of Tensors:', dif_result)
print('Multiply of Tensors:', mul_result)
print('Division of Tensors:', div_result)

Sum of Tensors: tf.Tensor([5 5 5], shape=(3,), dtype=int32)
Difference of Tensors: tf.Tensor([1 1 1], shape=(3,), dtype=int32)
Multiply of Tensors: tf.Tensor([6 6 6], shape=(3,), dtype=int32)
Division of Tensors: tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float64)


#### Element-wise Operations with Tensors:
- Element-wise operations in tensors are operations that are applied individually to each element of the tensors.

In [6]:
import tensorflow as tf

# Define tensors
a = tf.constant([3, 5, 7], dtype=tf.float32)
b = tf.constant([2, 6, 4], dtype=tf.float32)

# Check shapes
if a.shape != b.shape:
    raise ValueError("Tensors 'a' and 'b' must have have the same shape.")

# Check datatypes
if a.dtype != b.dtype:
    raise ValueError("Tensors 'a' and 'b' must have the same data type.")

#### Implementation code for element-wise operations:
- tf.minimum() - computes element-wise minimum of two tensors.
- tf.maximum() - computes element-wise maximum of two tensors.
- tf.abs() - computes element-wise absolute value.
- tf.math.log() - computes element-wise natural logorithm.
- tf.exp() - computes element-wise exponential.

In [7]:
# Element-wise operations
min_result = tf.minimum(a, b)
max_result = tf.maximum(a, b)
abs_result = tf.abs(a)
log_result = tf.math.log(tf.maximum(a, 1e-8))  # Ensure positive values for logarithm
exp_result = tf.exp(a)

print("Minimum:", min_result)
print("Maximum:", max_result)
print("Absolute value:", abs_result)
print("Logarithm:", log_result)
print("Exponential:", exp_result)

Minimum: tf.Tensor([2. 5. 4.], shape=(3,), dtype=float32)
Maximum: tf.Tensor([3. 6. 7.], shape=(3,), dtype=float32)
Absolute value: tf.Tensor([3. 5. 7.], shape=(3,), dtype=float32)
Logarithm: tf.Tensor([1.0986123 1.609438  1.9459101], shape=(3,), dtype=float32)
Exponential: tf.Tensor([  20.085537  148.41316  1096.6332  ], shape=(3,), dtype=float32)


### Aggregation and statistics Operations with Tensors:
- It provides several aggregation functions for statistical analysis using .reduce().
- Reduction operations in TensorFlow invilve performing operations across specific axes of a tensor, reducing the dimensionality of the tensor in the process.
- tf.reduce_mean() - is used to compute the mean along a specified axis(axis=0 means column-wise).

In [8]:
import tensorflow as tf
x = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
mean_result = tf.reduce_mean(x, axis=0)
print(mean_result)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


#### Logical AND and OR operations:
- tf.reduce_all - Computes the logical AND operations.
- tf.reduce_any - Computes the logical OR operations.

In [9]:
import tensorflow as tf

x = tf.constant([[True, False, True], [False, True, True]])
all_result = tf.reduce_all(x, axis=1)
any_result = tf.reduce_any(x, axis=0)

print(all_result)
print(any_result)

tf.Tensor([False False], shape=(2,), dtype=bool)
tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


#### log-space operations:
- tf.math.reduce_logsumexp() - Computes the logorithm of the sum of exponential of elements along a specified axis or axes.
- This is useful for numerical stability in log-space operations.

In [10]:
import tensorflow as tf

x = tf.constant([[1.0, 2.0, 3.0], [4.0,5.0,6.0]])

logsumexp_result = tf.math.reduce_logsumexp(x, axis=1)
print(logsumexp_result)

tf.Tensor([3.407606 6.407606], shape=(2,), dtype=float32)


#### Automatic Differentation with Tensors:
- tf.gradient() - enabling efficient computation of gradients for optimization algorithms such as gradient descent.
- Tensorflow's computational graph framework automatically computes derivatives of expressions with respect to their inputs.

In [11]:
import tensorflow as tf

x = tf.Variable(3.0)

def compute_gradient(x):
    with tf.GradientTape() as tape:
        y = x**2
    return tape.gradient(y,x)
gradient = compute_gradient(x)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)
