### What is string tensors?
- The string data type is used to represent string values. We use -
  - tf.string
- In this article, we will learn about the tf.string, exploring its operations, encoding/decoding techniques, comparison methods, real-world applications etc.
### How to create string tensors?


In [1]:
import tensorflow as tf

# Create a sclaer string tensor
scaler_string_tensor = tf.constant("Hello, TensorFlow!")
print(scaler_string_tensor)

# Create a vector of tsring tensor
vector_string_tensor = tf.constant(["Hello", "TensorFlow", "World"])
print(vector_string_tensor)

# Create a 2D matrix of string tensor
matrix_string_tensor = tf.constant([["Hello", "World"], ["TensorFlow","Rocks!"]])
print(matrix_string_tensor)

C:\Users\techs\anaconda3\New folder\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)
tf.Tensor([b'Hello' b'TensorFlow' b'World'], shape=(3,), dtype=string)
tf.Tensor(
[[b'Hello' b'World']
 [b'TensorFlow' b'Rocks!']], shape=(2, 2), dtype=string)


### Operations can be performed by String tensors?
- It provides a set of string operations that can be used on tf.string tensors.
- It support many operations, including concatenation, splitting, padding, and indexing.
#### concatenation:
- We create two string constants using tensorflow, join them together with a space seperator, and then prints the result as numpy array.
  - tf.strings.join(t1,t2, separator=" ")

In [2]:
import tensorflow as tf

t1 = tf.constant("Hello")
t2 = tf.constant("World!")
result = tf.strings.join([t1, t2],separator=" ")
print(result.numpy())

b'Hello World!'


#### Splitting:
- Creates a TensorFlow constant containing the sentence "Welcome to TensorFlow".
  - sentence = tf.constant("Welcome to tensorflow")
- Splits the sentence into words. This function splits the inputs strings(s) into substrings based on the provided delimiter. It returns a RaggedTensor containing the split substrings.
  - words = tf.strings.split(sentence)
- Then print the RaggedTensor object.
  - print(words)
#### Indexing:
- Creates a TensorFlow constant containing the sentence "Welcome to TensorFlow".
  - sentence = tf.constant("Welcome to tensorflow")
- Splits the sentence into ondividual characters, treating the inputs as UTF-8 encoded.
  - char = tf.strings.unicode_split(sentence, "UTF-8")
- Prints the first element of the char RaggedTensor, which corresponds to the first character of the sentence.
  - print(char[0])

In [9]:
import tensorflow as tf
sentence = tf.constant("Welcome to TensorFlow")
words = tf.strings.unicode_split(sentence, "UTF-8")
print(words)

import tensorflow as tf
sentence = tf.constant("Welcome to TensorFlow")
char = tf.strings.unicode_split(sentence, "UTF-8")
print('\n')
print(char[0])

tf.Tensor(
[b'W' b'e' b'l' b'c' b'o' b'm' b'e' b' ' b't' b'o' b' ' b'T' b'e' b'n'
 b's' b'o' b'r' b'F' b'l' b'o' b'w'], shape=(21,), dtype=string)


tf.Tensor(b'W', shape=(), dtype=string)


#### Encoding:
- To encode a Unicode string char into UTF-8 encoding, we use -
  - tf.strings.unicode_encode
#### Decoding:
- To decodes a UTF-8 encoded string encoded_str back to Unicode, we use -
  - tf.strings.unicode_decode

In [11]:
import tensorflow as tf

# Define the encodeing
char = tf.ragged.constant([22, 600])
encoded_str = tf.strings.unicode_encode(char, "UTF-8")
print(encoded_str)

# Define the Decoding
decoded_str = tf.strings.unicode_decode(encoded_str, "UTF-8")
print('\n')
print(decoded_str)

tf.Tensor(b'\x16\xc9\x98', shape=(), dtype=string)


tf.Tensor([ 22 600], shape=(2,), dtype=int32)


### How strings tensor can be used for comparison and matching?
- string tensors can be compared for equality, similarity, or matched using the regular expresions with tf.strings functions like tf.strings.regmax_match.
#### Comparison:
- The code compares two strings str1 and str2 using TensorFlow's function to check if they are equal.
  - tf.strings.compare

In [15]:
import tensorflow as tf
t1 = tf.constant(['Hello'])
t2 = tf.constant(['World'])
t3 = tf.equal(t1, t2)
print(t3)

t4 = tf.constant('Ten')
t5 = tf.constant('Ten')
t6 = tf.strings.regex_full_match(t4, t5)
print('\n')
print(t6)

tf.Tensor([False], shape=(1,), dtype=bool)


tf.Tensor(True, shape=(), dtype=bool)


### Working with Batched String Tensors:
- Efficiently handling batched string tensors is essential in many machine learning tasks.
#### Batching:
- The code splits a batch of sentences into words using -
  - tf.strings.split
#### Unbatching:
- The code joins the words in each sentence back into sentences using -
  - tf.strings.join

In [17]:
import tensorflow as tf

# Define the Batching
batched_sentences = tf.constant(["TensorFlow is awesome", "Machine learning is fun"])
words = tf.strings.split(batched_sentences)
print(batched_sentences)
print('\n')
print(words)

# Define the Unbatching
unbatched_sentences = tf.strings.join(words[0], separator="")
print('\n')
print(unbatched_sentences.numpy())

tf.Tensor([b'TensorFlow is awesome' b'Machine learning is fun'], shape=(2,), dtype=string)


<tf.RaggedTensor [[b'TensorFlow', b'is', b'awesome'],
 [b'Machine', b'learning', b'is', b'fun']]>


b'TensorFlowisawesome'


### String Tensor Preprocessing in TensorFlow Models:
- Preprocessing string data is crucial before feeding it into TensorFlow models.
- Utilizes tf.strings functions like tf.strings.lower, tf.strings.regex_replace, etc.. for preprocessing tasks.
#### Convert to lower:
- We can convert to lower case by using the -
  - tf.strings.lower()
#### Convert to Upper:
- We can convert to upper case by using the -
  - tf.strings.upper()

In [20]:
text = tf.constant("Hello, TensorFlow!")
processed_text1 = tf.strings.lower(text)
print(processed_text1)


processed_text2 = tf.strings.upper(text)
print(processed_text2)

tf.Tensor(b'hello, tensorflow!', shape=(), dtype=string)
tf.Tensor(b'HELLO, TENSORFLOW!', shape=(), dtype=string)


### Handling missing values in string tensors:
- Strategies like using default values or special tokens are essential for handling missing or empty string values in Tensorflow.
- We can use handling empty or missing values will be -
  - tf.strings.replace

In [21]:
str_with_missing = tf.constant("Hello Tensorflow <br /><b>contains string</b>")
str_with_default = tf.strings.regex_replace(str_with_missing, "<[^>]+>", "")
print(str_with_default)

tf.Tensor(b'Hello Tensorflow contains string', shape=(), dtype=string)
