### Variables in Tensorflow:
- TensorFlow is a python library for efficient numerical computing.
- It's foundation library that can be used to develop machine learning and deep learning models.
- Tensorflow is a high-level library. A variable is a state or value that can be modified by performing operations on it.
- In TensorFlow variables are created using the Variable() constructor.
#### Creating a variable:
- tf.Variable() - constructor is used to create a variable in TensorFlow.
#### Dimension, size, shape, and dtype of a TensorFlow variable:

In [2]:
import tensorflow as tf
tensor1 = tf.Variable([3,8])
print('The shape of the variable:',tensor1.shape)
print('The number of dimensions in the variable:', tf.rank(tensor1).numpy())
print('The size of the tensorflow variable:', tf.size(tensor1).numpy())
print('The datatype of the tensorflow variable is:', tensor1.dtype)

The shape of the variable: (2,)
The number of dimensions in the variable: 1
The size of the tensorflow variable: 2
The datatype of the tensorflow variable is: <dtype: 'int32'>


### Assigning or modifying the elements in the variable:
- We use the assign() method to modify the variable.
- It is more like indexing and then using the assign() method.
- There are more methods to assign or modify the variable such as Variable.assign_add() and Variable.assign_sub().
#### assign(), assign_add(), assign_sub():
- assign() - It is used to update or add a new value.
  - Syntax: assign(value, use_looking=False, name=None, read_value=True)
  - Where,
    - value - The new value for this variable.
    - use_looking - locking during assignment if "true".
- assign_add() - It is used for adding.
  - Syntax: assign_add(delta, use_looking=False, name=None, read_value=True)
  - Where,
    - delta - The value to be added to the variable(Tensor).
    - use_looking - During the operation, if True, utilise locking.
    - name - name of the operation.
- assign_sub() - It is used for subtracting.
  - Syntax: assign_sub(delta, use_looking=False, name=None, read_value=True)

In [12]:
import tensorflow as tf
tensor1 = tf.Variable([3,4])
print('Original:',tensor1)

# Adding Operation
tensor1.assign_add([1, 1])
print('Adding:',tensor1)

# Subtarcting Operation
tensor1.assign_sub([1,1])
print('Subtract:',tensor1)

Original: <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>
Adding: <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>
Subtract: <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>


#### Changing the shape of the variable:
- tf.reshape() - It is used to change the shape of the variable.
- The variable and shape must be passed.
#### Changing the datatype of the tensor:
- If you want the variable to have a particular data type we have to specify dtype while creating the variable.
- In this example, we specify the datatype will be float.

In [16]:
import tensorflow as tf
tensor1 = tf.Variable([[1, 2, 3, 4]])

# Reshape the tensor
tf.reshape(tensor1, shape=(2, 2))
print('Reshape:',tensor1)

# Change the Datatype
tensor2 = tf.Variable([1,2,3,4], dtype=float)
print('Change Datatype:',tensor2)


Reshape: <tf.Variable 'Variable:0' shape=(1, 4) dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>
Change Datatype: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>


####  Operations with Variables:
- We can perform addition, subtraction, multiplications, division, and many more operations with TensorFlow variables.

In [19]:
import tensorflow as tf

tensor1 = tf.Variable([3,4])
tensor2 = tf.Variable([5,6])
print('Addition of tensors:', tensor1+tensor2)
print('Subtarction of tensors:', tensor1-tensor2)
print('Multiplication of tensors:', tensor1*tensor2)
print('Division of tensors:', tensor1/tensor2)


import tensorflow as tf

tensor1 = tf.Variable([3,4])
tensor2 = tf.Variable([2])
output = tensor1 * tensor2
print('\n')
print(output)

Addition of tensors: tf.Tensor([ 8 10], shape=(2,), dtype=int32)
Subtarction of tensors: tf.Tensor([-2 -2], shape=(2,), dtype=int32)
Multiplication of tensors: tf.Tensor([15 24], shape=(2,), dtype=int32)
Division of tensors: tf.Tensor([0.6        0.66666667], shape=(2,), dtype=float64)


tf.Tensor([6 8], shape=(2,), dtype=int32)


#### Hardware Selection for Variables:
- .device - attribute is used.
- We may utilize it to see what type of device is used to process our variable.

In [20]:
import tensorflow as tf

tensor1 = tf.Variable([3,4])
print('The type of hardware variable used:' +tensor1.device)

The type of hardware variable used:/job:localhost/replica:0/task:0/device:CPU:0
