### What is NumPy ?
- NumPy is python library and used for working with arrays.
- NumPy is short for "Numerical Python"
### Why Use NumPy?
- In Python, we have lists that serve the purpose of arrays, but they are very slow.
- NumPy aim is to provide a array Object that is 50x faster than than traditional arrays.
- NumPy arrays are stored at one continuous place in memory unlike lists.

### NumPy Creating Arrays
- We can create NumPy ndarray() object by using array() function. 

In [2]:
import numpy as np
arr=np.array([7,78,9,63])
print(arr)
print(type(arr))

[ 7 78  9 63]
<class 'numpy.ndarray'>


### Dimensions in Arrays
- 0-D Arrays : Each value in an array is a 0-D array.
- 1-D Arrays : An array that has 0-D arrays as its elements is called 1-D arrays.
- 2-D Arrays : An array that has 1-D arrays as its elements is called 2-D arrays.
- 3-D Arrays : An array that has 2-D arrays as its elements is called 3-D arrays.
### Check the dimensions
- ndim() : Tells the how many dimensions the array have.

In [11]:
import numpy as np
arr=np.array(78)
print(arr)

import numpy as np
arr=np.array([1,4,7,2])
print(arr)

import numpy as np
arr=np.array([[1,4,7],[2,5,8]])
print(arr)

import numpy as np
arr=np.array([[[1,5,9],[7,5,3]],[[2,5,8],[4,6,1]]])
print(arr)

import numpy as np
arr=np.array([1,5,9,7,6,3])
print(arr.ndim)

import numpy as np
arr=np.array([[1,5,9],[8,3,4]],ndmin=5)
print(arr.ndim)

78
[1 4 7 2]
[[1 4 7]
 [2 5 8]]
[[[1 5 9]
  [7 5 3]]

 [[2 5 8]
  [4 6 1]]]
1
5


### NumPy Array Indexing
- Array indexing is the same as accessing an array element.
- 2-D Arrays : We can use comma seperated integers representing the dimensions and the index of the elements.
  Where index represent the column and dimension represents the row.
- 3-D Array : Access the third element of the second array of the first array.
### Negative Indexing
- Use negative indexing to access an array from the end.

In [16]:
import numpy as np
arr=np.array([1,4,7,8,5,2])
print(arr[3])

import numpy as np
arr=np.array([[1,5,9],[8,4,3]])
print(arr[0,1])

import numpy as np
arr=np.array([[[1,4,7],[2,5,8]],[[3,6,9],[7,8,9]]])
print(arr[0,1,2])

import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

8
5
8
Last element from 2nd dim:  10


### NumPy Array Slicing
- Taking elements from one given index to another given index.
- The result includes the start index, but excludes the end index.
### Negative Slicing
- Use the minus operator to refer to an index from the end.
### STEP
- step : Return every other element from index starting index point to another index point.

In [11]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:4])
print(arr[1:6])
print(arr[4:])
print(arr[:5])
print(arr[-3:-1])

import numpy as np
arr=np.array([1,4,7,2,5,8,3,6,9])
print(arr[::2])

import numpy as np
arr=np.array([[1,4,7,2,5,8,3,6,9],[7,4,1,8,5,2,9,6,3]])
print(arr[1,1:5])
print(arr[0:4,4:6])
print(arr[0:2, 2])

[2 3 4]
[2 3 4 5 6]
[5 6 7 8 9]
[1 2 3 4 5]
[7 8]
[1 7 5 3 9]
[4 1 8 5]
[[5 8]
 [5 2]]
[7 1]


### Data Types in NumPy
- NumPy has some extra data types:
- i : integer.
- f : float.
- b : boolean.
- u : unsigned integer.
- S : string.
- M : DateTime.
- c : complex float.
- m : timedelta.
- V : void
- O : object
### Check type of array
- dtype : Returns the data type of the array.
- astype: To change existing array type of required array type.
- We can also create the Defined datatype.

In [15]:
import numpy as np
arr1=np.array(['Cat','Dog','Bird','Rabbit'])
arr2=np.array([True,False,True,True])
arr3=np.array([12,3,4,5,6])
arr4=np.array([2.3,5.68,14.9])
arr5=np.array(['2025-02-12'])
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)
print(arr5.dtype)

import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

import numpy as np
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

<U6
bool
int64
float64
<U10
[b'1' b'2' b'3' b'4']
|S1
[ True False  True]
bool


### NumPy Array Copy vs View
- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.
### Check if Array Owns its Data
- base : attribute refers to the original object.
- The copy returns None.
- The view returns the original array.

In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)


import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)


import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
None
[1 2 3 4 5]


### NumPy Array Shape
- shape : The shape of an array is the number of elements in each dimension.
- shape that returns a tuple with each index having the number of corresponding elements.
### NumPy Array Reshaping
- reshape : By reshaping we can add or remove dimensions or change number of elements in each dimension.
- Eg : arr.shape(4,3) - The outermost dimension will have 4 arrays, each with 3 elements.[1-D to 2-D]
- Eg : arr.reshape(2,3,2) - The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements.[2-D to 3-D]
### Flattening the arrays
- Flattening array means converting a multidimensional array into a 1D array.
- We can use reshape(-1) to do this.

In [20]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6]


### NumPy Array Iterating 1-D, 2-D, 3-D Arrays
- Iterating means going through elements one by one.
### Iterating Arrays Using nditer()
- nditer() - It is a helping function that can be used from very basic to very advanced iterations.
- It will reduce the usage of for more for-loops.
### Iterating Array With Different Data Types
- op_dtypes - use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
- flags=['buffered'] - NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].
### Enumerated Iteration Using ndenumerate()
- Enumeration means mentioning sequence number of somethings one by one.
- ndenumerate() - Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

import numpy as np
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

import numpy as np
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

### NumPy Joining Array
- concatenate() - By adding two arrays.
### Joining Arrays Using Stack Functions, Rows, Columns, Height.
- stack() - Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
- hstack() - To stack along rows.
- vstack() - To stack along columns.
- dstack() - To stack along height, which is same as depth

In [27]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


### NumPy Splitting Array
- array_split() -  For splitting arrays, we pass it the array we want to split and the number of splits.
- The return value is a list containing arrays.
- In addition, you can specify which axis you want to do the split around.
- The example below also returns three 2-D arrays, but they are split along the column (axis=1).

In [28]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
     

### NumPy Searching Arrays
- where() - To search an array use this method.
- You search an array for a certain value and return the indexs that get a match.
### searchsorted()
- searchsorted() - performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
- By default, It will start with left side on words and we can also change search direction.
- side='right' - To return the right most index.

In [6]:
import numpy as np
arr=np.array([1,4,7,2,58,1,1,2])
newarr=np.where(arr == 1)
newarr1=np.where(arr%2 == 1)
newarr2=np.where(arr%2 == 0)
print(newarr)
print(newarr1)
print(newarr2)

import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

import numpy as np
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

(array([0, 5, 6]),)
(array([0, 2, 5, 6]),)
(array([1, 3, 4, 7]),)
2
[1 2 3]


### NumPy Sorting Arrays, 2-D Arrays
- sort() - To sort the elements in an ordered sequence.
  

In [7]:
import numpy as np
arr=np.array([1,4,7,2,5,8])
arr1=np.array([True,False,True])
arr2=np.array(['Cat','Dog','Bird','Apple'])
print(np.sort(arr))
print(np.sort(arr1))
print(np.sort(arr2))

[1 2 4 5 7 8]
[False  True  True]
['Apple' 'Bird' 'Cat' 'Dog']
