### NumPy ufuncs
- ufuncs - stands for Universal Functions.
- It is used for implement vectorization in NumPy, which is faster than iterating over elements.
### NumPy Add Lists
- add(x,y) - To get same list like zip(x,y).

In [2]:
x=[1,4,7]
y=[2,5,8]
z=[]
for i, j in zip(x,y):
    z.append(i+j)
print(z)

import numpy as np
x=[1,4,7]
y=[2,5,8]
z=np.add(x,y)
print(z)

[3, 9, 15]
[ 3  9 15]


### How To Create Your Own ufunc
- Same like normal functions in Python.we can create our own ufunc then you add it to your NumPy func library called frompyfunc() method.
- The frompyfunc() method takes arguments:
- function - The name of the function.
- inputs - The no of inputs arguments(arrays).
- outputs - The no of output arrays. 

In [4]:
import numpy as np
def myadd(x,y):
    return x+y
myadd=np.frompyfunc(myadd,2,1)
print(myadd([1,4,7],[2,5,8]))

[3 9 15]


### ufunc Simple Arithmetic
- add() - sum of two arrays.
- subtract() - subtract the two arrays.
- multiply() - multiply vales of one array to another array.
- divide() - Divide values from one array from another array.
- power() - Power of one array to another array.
- mod() & remainder() - Return the remainder of the values in the first array corresponding to the values in the second array then return in new array.
- divmod() - return both quotient and mod.The return values is two arrays.first array contain quotient and second array contain mod.
- absolute() & abs() - To perform sam operation on elements.Mostly we prefer absolute() to avoid errors.

In [10]:
import numpy as np
arr1=np.array([1,4,7])
arr2=np.array([2,5,8])
newarr1=np.add(arr1,arr2)
newarr2=np.subtract(arr1,arr2)
newarr3=np.multiply(arr1,arr2)
newarr4=np.divide(arr1,arr2)
newarr5=np.power(arr1,arr2)
newarr6=np.mod(arr1,arr2)
newarr7=np.remainder(arr1,arr2)
print(newarr1)
print(newarr2)
print(newarr3)
print(newarr4)
print(newarr5)
print(newarr6)
print(newarr7)


import numpy as np
arr1=np.array([1,4,7])
arr2=np.array([2,5,8])
newarr1=np.divmod(arr1,arr2)
print(newarr1)

import numpy as np
arr=np.array([-1,4,-7,2,5,-8])
newarr=np.absolute(arr)
print(newarr)

[ 3  9 15]
[-1 -1 -1]
[ 2 20 56]
[0.5   0.8   0.875]
[      1    1024 5764801]
[1 4 7]
[1 4 7]
(array([0, 0, 0]), array([1, 4, 7]))
[1 4 7 2 5 8]


### ufunc Rounding Decimals
- There arew primarliy five ways of rounding decimals:
- trunc() & fix() - Remove decimals, and return the float number close to zero.
- around() - It increments preceding digit (or) decimal by 1 if>=5 elsoe do nothing.
- floor() - It roundoff to decimal integer to nearestlowest integer.
- ceil() - It roundoff to decimal integer to nearest upper integer.
   

In [16]:
import numpy as np
arr=np.array([-32.596,-96.3145])
newarr=np.trunc(arr)
newarr1=np.fix(arr)
print(newarr)
print(newarr1)

import numpy as np
arr=np.array([3.6145,2])
newarr=np.around(arr)
print(newarr)

import numpy as np
arr=np.array([-36.145,-96.3145])
newarr=np.floor(arr)
print(newarr)

import numpy as np
arr=np.array([-85.123,75.15])
newarr=np.ceil(arr)
print(newarr)

[-32. -96.]
[-32. -96.]
[4. 2.]
[-37. -97.]
[-85.  76.]


### ufunc NumPy Logs
- log2() - To Perform log at base 2.
- log() - To Perform log at base (or) log at base e.
- log10() - To Perform log at base 10.
- NumPy does not provide any function to log.so we cau use frompyfunc() function along with in-built function math.log() with two parameters and one output parameters.

In [20]:
import numpy as np
arr=np.arange(1,10)
newarr=np.log2(arr)
print(newarr)

import numpy as np
arr=np.arange(1,10)
newarr=np.log(arr)
print(newarr)

import numpy as np
arr=np.arange(1,10)
newarr=np.log10(arr)
print(newarr)

from math import log
import numpy as np
arr=np.frompyfunc(log,2,1)
newarr=arr(100,15)
print(newarr)

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
1.7005483074552052


### ufunc NumPy Summations
- Addition is done between two arguments whereas summation happens over n elements.
- If you specify axis=1 then NumPy will sum the numbers in each arrays.
- Cummulative sum - Partially adding elements in array.
- cumsum() - To perform operation by using this. 

In [25]:
import numpy as np
arr1=np.array([1,4,7])
arr2=np.array([2,5,8])
newarr=np.add(arr1,arr2)
newarr1=np.sum([arr1,arr2])
print(newarr1)
print(newarr)

import numpy as np
arr1=np.array([1,4,7])
arr2=np.array([2,5,8])
newarr=np.sum([arr1,arr2],axis=1)
print(newarr)

import numpy as np
arr=np.array([1,4,7])
newarr=np.cumsum(arr)
print(newarr)

27
[ 3  9 15]
[12 15]
[ 1  5 12]


### ufunc NumPy Products
- prod() - To find the product of elements.
- If you specify axis=1 then ,NumPy will return the product of each array.
- cumprod() - To product partially.

In [29]:
import numpy as np
arr=np.array([1,4,7])
newarr=np.prod(arr)
print(newarr)

import numpy as np
arr1=np.array([1,4,7])
arr2=np.array([2,5,8])
newarr=np.prod([arr1,arr2])
print(newarr)

import numpy as np
arr1=np.array([1,4,7])
arr2=np.array([2,5,8])
newarr=np.prod([arr1,arr2],axis=1)
print(newarr)

28
2240
[28 80]


### ufunc NumPy Differences
- diff() - To Perform Discrete difference.
- n - We can perform this operation repeatedly by giving parameter n.

In [32]:
import numpy as np
arr=np.array([1,4,7,2,5,8])
newarr=np.diff(arr)
print(newarr)

import numpy as np
arr=np.array([1,4,7,8,5,2])
newarr=np.diff(arr,n=2)
print(newarr)

[ 3  3 -5  3  3]
[ 0 -2 -4  0]


### ufunc NumPy Differences
- lcm() - The Lowest Common Multiple is the smallest number that is a common multiple of two numbers.
- reduce() - To find the Lowest Common Multiple of all values in an array.
### ufunc NumPy GCD Greatest Common Divisor
- gcd() - The Greatest Common Divisior is the biggest number that is a common factor of both the numbers.
- reduce() - To find the Lowest Common Multiple of all values in an array.

In [35]:
import numpy as np
num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print(x)

import numpy as np
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

import numpy as np
num1 = 4
num2 = 6
x = np.gcd(num1, num2)
print(x)

import numpy as np
arr = np.array([3, 6, 9])
x = np.gcd.reduce(arr)
print(x)

12
18
2
3


### ufunc NumPy Trigonometric and Hyperbolic Functions
- sin(), cos() & tan() - It take values in radians and produce the corresponding sin, cos and tan values.
- deg2rad() - Convert Degrees Into Radians.
- rad2deg() - Convert Radians Into Degrees
- arcsin(), arccos() & arctan() - It produce radian values for corresponding sin, cos and tan values given.
- hypot() - It takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.
- sinh(), cosh() & tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values.
- arcsinh(), arccosh() & arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.

In [38]:
import numpy as np
x = np.sin(np.pi/2)
print(x)

import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

import numpy as np
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

import numpy as np
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

import numpy as np
x = np.arcsin(1.0)
print(x)

import numpy as np
base = 3
perp = 4
x= np.hypot(base, perp)
print(x)

import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cosh(arr)
print(x)

import numpy as np
arr = np.array([0.1, 0.2, 0.5])
x = np.arctanh(arr)
print(x)

1.0
[1.         0.8660254  0.70710678 0.58778525]
[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]
1.5707963267948966
5.0
[2.50917848 1.60028686 1.32460909 1.20397209]
[0.10033535 0.20273255 0.54930614]


### ufunc NumPy Set Operations
- A set in mathematics is a collection of unique elements.
- unique() - To find unique elements from any array.
- unique1d() - To find the unique values of two arrays
- intersect1d() - To find only the values that are present in both arrays.
- setdiff1d() - To find only the values in the first set that is NOT present in the seconds set.
- setor1d() - To find only the values that are NOT present in BOTH sets.

In [39]:
import numpy as np
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)

import numpy as np
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr)

import numpy as np
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setxor1d(set1, set2, assume_unique=True)
print(newarr)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]
